### ISSUE TITLE
How run saga background task in server?

### ISSUE THREAD

**Issue by tronghiep92** [bmealhouse/next-redux-saga#2]
Hi Brent,
Thank you so much for the package, it helped me a lot.
But I have a small problem.
I'm cloned example https://github.com/zeit/next.js/tree/master/examples/with-redux-saga and changed in file `saga.js`
```
function * rootSaga () {
  yield all([
    call(runClockSaga),
    takeLatest(actionTypes.LOAD_DATA, loadDataSaga)
  ])
}
```
to 

```
function* rootSaga() {
  yield all([call(runClockSaga), fork(loadDataSaga)]);
}
```
It still works well. Because I want to load initial data in server for all pages.
But checked Network tab in the browser, I found out `fetch https://jsonplaceholder.typicode.com/users` in the client(XHR) not on the server.
Look at the picture below. Please help me fix it and thank so much.

<img width="553" alt="screen shot 2017-09-02 at 3 40 17 pm" src="https://user-images.githubusercontent.com/4768095/29994242-0ea95368-8ff5-11e7-8fce-0b5d90619cb9.png">

**Comment by bmealhouse** [comment]
@tronghiep92 - Using `fork` will not achieve that behavior.

In your code example, `fork` is getting called on the server, but redux-saga's `END` action is causing the server to return a response to the client, before `loadDataSaga` can return it's results.  Since no results are sent to the client, the data is fetched again from the client-side.

For sever-side rendering to work, you need to put your saga(s) in a running state so that they are not terminated by redux-saga's `END` action.  Look at **pages/index.js** `getInitialProps` to see how this is done:

```js
if (!store.getState().placeholderData) {
  store.dispatch(loadData())
}
```

By using the `takeLatest` saga (not `fork`) and dispatching the `loadData()` action, this puts the saga in a running state and forces the server to wait until it has received results, before sending a response to the client.

If you want to load initial data across all pages, I suggest creating a HOC that triggers the `loadData()` action in `getInitialProps`.  Then wrap all your pages with the HOC.

**Comment by tronghiep92** [comment]
@bmealhouse 
Thank you, I solved the problem.

**Comment by bmealhouse** [comment]
@tronghiep92 - Did you use a HOC or come up with a different solution?

**Comment by tronghiep92** [comment]
@bmealhouse 
I'm using `process.browser`. Do nothing if it is on the client.

**Comment by bmealhouse** [comment]
@tronghiep92 - Thanks for sharing.

So the data was returned from the server using `fork`, but it was also getting requested on the client.  That make sense.  Sorry for the confusion in my initial response.

Glad you found a solution!
