### ISSUE TITLE
page is rendered before sagas are done on client side

### ISSUE THREAD

**Issue by pavel06081991** [bmealhouse/next-redux-saga#54]
On the server side render method is called only after sagas from getInitialProps are done. But on the client side render method is not waiting for finishing sagas. Is it a bug or it is expected behavior?

**Comment by bbortt** [comment]
Hi @pavel06081991 
It is an expected behaviour. `redux-saga` is a way of *asynchronously* handling side effects ;)
From the docs:
>redux-saga is a library that aims to make application side effects (i.e. asynchronous things like data fetching and impure things like accessing the browser cache) easier to manage, more efficient to execute, easy to test, and better at handling failures.

**Comment by pavel06081991** [comment]
@bbortt yep but on the server side render method of pages is waiting for sagas are done when you call sagas in getInitialProps. On the other hand on the client side it is not waiting. Why next-redux-saga has different behavior for the server and the client sides?

**Comment by bbortt** [comment]
Yes, it is an expected behaviour. Because the initial load (ssr) shall return a full page including all data, so the client can already display something without any white page being displayed. Meanwhile the client will launch `react`, re-render the page and check all data, but this is handled asynchronously. Otherwise we would heavily impact the user experience as he could not navigate the page for quit some time.

**Comment by pavel06081991** [comment]
@bbortt thanks for clarification. Just wanted to be sure that all works good and I've not break anything while using next-redux-saga

**Comment by bbortt** [comment]
@pavel06081991 no problem :) hope you'll have fun 🚀
