### ISSUE TITLE
Redux State is not updated when store.dispatch() is called from getInitialProps in _app.js

### ISSUE THREAD

**Issue by rehan-sattar** [bmealhouse/next-redux-saga#66]
Hi, I'm having an issue related to dispatching actions from `getInitialProps` . I have an application which is using redux saga. Everything works well. When I dispatch an action from the `_app.js` file. The action is dispatched and everything is okay till the reducer. Now the reducer is getting the `payload` but it's not updating the redux store's state.

Here is my `_app.js`
```js
class MyApp extends App {
  static async getInitialProps({ Component, ctx }) {
    let pageProps = {};
    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps({ ctx });
    }
    const { store, asPath } = ctx;
    const lang = asPath.substring(1, 3);
    const terms = readTerms(lang);
    await store.dispatch(fetchAllTerms(terms));
    return { pageProps };
  }

  render() {
    const { Component, pageProps, store } = this.props;
    return (
    
        <Provider store={store}>
          <Component {...pageProps} />
        </Provider>
    );
  }
}

export default withRedux(() => store)(withReduxSaga(MyApp));
```

Can anyone help me with this ?

**Comment by bbortt** [comment]
Can you post the reducer's code too, please?

**Comment by rehan-sattar** [comment]
```js
import { LOAD_TERMS, LOAD_TERMS_SUCCESS, LOAD_TERMS_ERROR } from './types';

const initialState = {
  data: [],
  loading: false,
  error: ''
};

const termsReducer = (state = initialState, { type, payload }) => {
  switch (type) {
    case LOAD_TERMS:
      return { ...state, loading: true };
    case LOAD_TERMS_SUCCESS:
      // Here I get the data which I want. But after that it's not updated. Also I'm getting all the logs in my terminal. Not in browsers' console.
      console.log('PAYLOAD:::', payload); 
      return { ...state, data: payload };
    case LOAD_TERMS_ERROR:
      return { ...state, error: payload };
    default:
      return state;
  }
};

export { termsReducer };

```

**Comment by bbortt** [comment]
Many thanks.

> // Here I get the data which I want. But after that it's not updated. Also I'm getting all the logs in my terminal. Not in browsers' console.

That is as expected. This library (or rather `zeit/next.js`) does support server side rendering (which the method `getInitialProps` was made for). The initial trigger will render your page once on the server side (e.g. invoke `getInitialProps`) and then again if you change the route on client side.

However, I think you ran into this:
```
> Attention: Synchronous HOC is no longer supported since version 4.0.0!
```
Since `redux` is based on channels, we can no longer support synchronous dispatching, neither server nor client side. Asynchronous, event based side effect management, that is what `redux` was designed for. As your `_app.js` and your reducer do look fine, I just think the side effect is not fast enough and the channel was already closed (the html returned to the client) at the time the store would have updated.

If you want to debug this problem further, you could create a custom middleware for `redux`. Then look at which time state updates were published compared to the `END` dispatch, which closes the channel.

Quick guess. I would have to "get my hands dirty" on some code if you need more detailed investigation ;)

**Comment by rehan-sattar** [comment]
Okay, I understand, For now I have resolved it by using `componentDidMount` .
I have access to the browser api here & the dispatching of action is working similar to client side. As It's running on client I guess. 

```js
  componentDidMount() {
    const lang = window.location.pathname.substring(1, 3);
    const terms = readTerms(lang);
    this.props.store.dispatch(fetchAllTerms(terms));
  }```

Btw thanks @bbortt  !!

**Comment by bbortt** [comment]
Yea, `componentDidMount` will be executed on the client side, there you can fetch your data ;) I'd recommend using *synchronous* calls when server side rendering only for the most important requests (like access checks). Then fetching the rest on client side.. clients these days are fast as f*** anyways ;)
No problem.
